name: Generate IP Lists

on:
  schedule:
    # Runs once a day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Compile CLI
        run: go build  -ldflags "-s -w" .

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: whois
          version: 1.0

      - name: Create Applebot IP-List
        id: applebot
        run: |
          curl -sL https://search.developer.apple.com/applebot.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/applebot.txt || exit 1
          [ -s ips/applebot.txt ] || git checkout -- ips/applebot.txt
        continue-on-error: true

      - name: Generate GoogleBot IP-List # Source: https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot
        id: googlebot
        run: |
          curl -sL https://developers.google.com/static/search/apis/ipranges/googlebot.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/googlebot.txt || exit 1
          [ -s ips/googlebot.txt ] || git checkout -- ips/googlebot.txt
        continue-on-error: true

      - name: Generate Google Special Crawlers # Source: https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot
        id: google-special
        run: |
          curl -sL https://developers.google.com/static/search/apis/ipranges/special-crawlers.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/google-special.txt || exit 1
          [ -s ips/google-special.txt ] || git checkout -- ips/google-special.txt
        continue-on-error: true

      - name: Generate Google User-triggered Fetchers # Source: https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot
        id: google-user-triggered
        run: |
          curl -sL https://developers.google.com/static/search/apis/ipranges/user-triggered-fetchers.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/google-fetchers.txt || exit 1
          curl -sL https://developers.google.com/static/search/apis/ipranges/user-triggered-fetchers-google.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean >> ips/google-fetchers.txt || exit 1
          [ -s ips/google-fetchers.txt ] || git checkout -- ips/google-fetchers.txt
        continue-on-error: true

      - name: Generate BingBot IP-List
        id: bingbot
        run: |
          curl -sL https://www.bing.com/toolbox/bingbot.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/bingbot.txt || exit 1
          [ -s ips/bingbot.txt ] || git checkout -- ips/bingbot.txt
        continue-on-error: true

      - name: Generate FacebookBot IP-List # Source: https://developers.facebook.com/docs/sharing/webmasters/crawler/
        id: facebookbot
        run: |
          whois -h whois.radb.net -- '-i origin AS32934' | grep ^route | awk '{gsub("(route:|route6:)","");print}' | awk '{gsub(/ /,""); print}' | ./iplists clean > ips/facebookbot.txt || exit 1
          [ -s ips/facebookbot.txt ] || git checkout -- ips/facebookbot.txt
        continue-on-error: true

      - name: Generate DuckDuckBot IP-List # Source: https://help.duckduckgo.com/duckduckgo-help-pages/results/duckduckbot/
        id: duckduckbot
        run: |
          curl -sL https://raw.githubusercontent.com/duckduckgo/duckduckgo-help-pages/master/_docs/results/duckduckbot.md | grep "^\- " | awk '{gsub("-",""); print}' | awk '{gsub(/ /,""); print}' | ./iplists clean > ips/duckduckbot.txt || exit 1
          [ -s ips/duckduckbot.txt ] || git checkout -- ips/duckduckbot.txt
        continue-on-error: true

      - name: Get UptimeRobot IP List # Source: https://uptimerobot.com/help/locations/
        id: uptimerobot
        run: |
          curl -sL https://uptimerobot.com/inc/files/ips/IPv4andIPv6.txt | ./iplists clean > ips/uptimerobot.txt || exit 1
          [ -s ips/uptimerobot.txt ] || git checkout -- ips/uptimerobot.txt
        continue-on-error: true

      - name: Get Pingdom IP List # Source: https://documentation.solarwinds.com/en/success_center/pingdom/content/topics/pingdom-probe-servers-ip-addresses.htm
        id: pingdom
        run: |
          curl -sL https://my.pingdom.com/probes/ipv4 | ./iplists clean > ips/pingdom.txt || exit 1
          curl -sL https://my.pingdom.com/probes/ipv6 | ./iplists clean >> ips/pingdom.txt || exit 1
          [ -s ips/pingdom.txt ] || git checkout -- ips/pingdom.txt
        continue-on-error: true

      - name: Get Stripe Webhook IP List # Source: https://stripe.com/docs/ips
        id: stripe-webhooks
        run: |
          curl -sL https://stripe.com/files/ips/ips_webhooks.txt | ./iplists clean > ips/stripe-webhooks.txt || exit 1
          [ -s ips/stripe-webhooks.txt ] || git checkout -- ips/stripe-webhooks.txt
        continue-on-error: true

      - name: Get Cloudflare IP List # Source: https://www.cloudflare.com/ips/
        id: cloudflare
        run: |
          curl -sL https://www.cloudflare.com/ips-v4 | ./iplists clean > ips/cloudflare.txt || exit 1
          echo "" >> ips/cloudflare.txt # join lists with new line (will be filtered out later)
          curl -sL https://www.cloudflare.com/ips-v6 | ./iplists clean >> ips/cloudflare.txt || exit 1
          cat ips/cloudflare.txt | ./iplists clean > ips/cloudflare.txt.tmp
          mv ips/cloudflare.txt.tmp ips/cloudflare.txt
          [ -s ips/cloudflare.txt ] || git checkout -- ips/cloudflare.txt
        continue-on-error: true

      - name: Get OpenAI IP List # Source: https://platform.openai.com/docs/gptbot
        id: openai
        run: |
          curl -sL https://openai.com/searchbot.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/openai.txt || exit 1
          curl -sL https://openai.com/chatgpt-user.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean >> ips/openai.txt || exit 1
          curl -sL https://openai.com/gptbot.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean >> ips/openai.txt || exit 1
          [ -s ips/openai.txt ] || git checkout -- ips/openai.txt
        continue-on-error: true

      - name: Get PerplexityBot IP List # https://docs.perplexity.ai/guides/bots
        id: perplexity-bot
        run: |
          curl -sL https://www.perplexity.com/perplexitybot.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/perplexity-bot.txt || exit 1
          [ -s ips/perplexity-bot.txt ] || git checkout -- ips/perplexity-bot.txt
        continue-on-error: true

      - name: Get Perplexity User IP List # https://docs.perplexity.ai/guides/bots
        id: perplexity-user
        run: |
          curl -sL https://www.perplexity.com/perplexity-user.json | jq -r '.prefixes[].ipv6Prefix,.prefixes[].ipv4Prefix | select( . != null )' | ./iplists clean > ips/perplexity-user.txt || exit 1
          [ -s ips/perplexity-user.txt ] || git checkout -- ips/perplexity-user.txt
        continue-on-error: true

      - name: Get Oracle IP List # https://docs.oracle.com/en-us/iaas/Content/General/Concepts/addressranges.htm
        id: oracle
        run: |
          curl -sL https://docs.oracle.com/en-us/iaas/tools/public_ip_ranges.json | jq -r '.regions[] | [.cidrs][] | .[].cidr | select(. != null)' | ./iplists clean > ips/oracle.txt || exit 1
          [ -s ips/oracle.txt ] || git checkout -- ips/oracle.txt
        continue-on-error: true

      - name: Get StatusCake IP List # https://www.statuscake.com/kb/knowledge-base/what-are-your-ips/
        id: statuscake
        run: |
          curl -sL https://app.statuscake.com/Workfloor/Locations.php?format=txt | ./iplists clean > ips/statuscake.txt || exit 1
          [ -s ips/statuscake.txt ] || git checkout -- ips/statuscake.txt
        continue-on-error: true

      - name: Generate Twitterbot IP-List # Source: https://developer.x.com/en/docs/x-for-websites/cards/guides/troubleshooting-cards#validate_twitterbot
        id: twitterbot
        run: |
          whois -h whois.radb.net -- '-i origin AS13414' | grep ^route | awk '{gsub("(route:|route6:)","");print}' | awk '{gsub(/ /,""); print}' | ./iplists clean > ips/twitterbot.txt || exit 1
          [ -s ips/twitterbot.txt ] || git checkout -- ips/twitterbot.txt
        continue-on-error: true

      - name: Generate Yahoo IP-List # Source: https://senders.yahooinc.com/mail-proxy-servers/
        id: yahoo
        run: |
          curl -sL https://geoip.yahoo.net/georeport.csv | awk -F, '{print $1}' | ./iplists clean > ips/yahoo.txt || exit 1
          [ -s ips/yahoo.txt ] || git checkout -- ips/yahoo.txt
        continue-on-error: true

      - name: Generate Iframely IP-List # Source: https://iframely.com/docs/about
        id: iframely
        run: |
          curl -sL https://iframely.com/ips-v4 | ./iplists clean > ips/iframely.txt || exit 1
          curl -sL https://iframely.com/ips-v6 | ./iplists clean >> ips/iframely.txt || exit 1
          [ -s ips/iframely.txt ] || git checkout -- ips/iframely.txt
        continue-on-error: true

      - name: Generate Internet Archive IP-List
        id: internet-archive
        run: |
          whois -h whois.radb.net -- '-i origin AS7941' | grep ^route | awk '{gsub("(route:|route6:)","");print}' | awk '{gsub(/ /,""); print}' | ./iplists clean > ips/internet-archive.txt || exit 1
          [ -s ips/internet-archive.txt ] || git checkout -- ips/internet-archive.txt
        continue-on-error: true

      - name: Generate proxy IP-List # multiple sources
        id: proxies
        run: |
          curl -sL "https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&proxy_format=protocolipport&format=text" | awk -F"//" '{print $2}' | awk -F":" '{print $1}' | ./iplists clean > $RUNNER_TEMP/proxies.txt || exit 1 
          curl -sL https://api.openproxylist.xyz/http.txt | awk -F":" '{print $1}' | ./iplists clean >> $RUNNER_TEMP/proxies.txt || exit 1
          curl -sL https://api.openproxylist.xyz/https.txt | awk -F":" '{print $1}' | ./iplists clean >> $RUNNER_TEMP/proxies.txt || exit 1
          curl -sL https://api.openproxylist.xyz/socks4.txt | awk -F":" '{print $1}' | ./iplists clean >> $RUNNER_TEMP/proxies.txt || exit 1
          curl -sL https://api.openproxylist.xyz/socks5.txt | awk -F":" '{print $1}' | ./iplists clean >> $RUNNER_TEMP/proxies.txt || exit 1
          cat $RUNNER_TEMP/proxies.txt | sort -u > ips/proxies.txt || exit 1
          [ -s ips/proxies.txt ] || git checkout -- ips/proxies.txt
        continue-on-error: true

      - name: Generate iCloud Private Relay IP-List # Source: https://blog.cloudflare.com/icloud-private-relay/
        id: icloud-private-relay
        run: |
          curl -sL https://mask-api.icloud.com/egress-ip-ranges.csv | awk -F, '{print $1}' | ./iplists clean | sort -u > ips/icloud-private-relay.txt || exit 1
          [ -s ips/icloud-private-relay.txt ] || git checkout -- ips/icloud-private-relay.txt
        continue-on-error: true

      # VPN must come after iCloud Private Relay as those are then removed from this list
      - name: Generate VPN IP-List # Source: https://github.com/X4BNet/lists_vpn
        id: vpn
        run: |
          curl -sL https://raw.githubusercontent.com/X4BNet/lists_vpn/refs/heads/main/output/vpn/ipv4.txt | ./iplists clean | sort -u > ips/vpn.txt || exit 1
          ./iplists prune ips/vpn.txt ips/icloud-private-relay.txt || exit 1
          [ -s ips/vpn.txt ] || git checkout -- ips/vpn.txt
        continue-on-error: true

      - name: Generate AbuseIPDB 100d IP-List # Source: https://github.com/borestad/blocklist-abuseipdb
        id: abuseipdb-100d
        run: |
          curl -sL https://raw.githubusercontent.com/borestad/blocklist-abuseipdb/refs/heads/main/abuseipdb-s100-30d.ipv4 | awk -F" " '{print $1}' | ./iplists clean | sort -u > ips/abuseipdb-100d.txt || exit 1
          [ -s ips/abuseipdb-100d.txt ] || git checkout -- ips/abuseipdb-100d.txt
        continue-on-error: true

      - name: Commit & push updated IP-Lists
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Daily auto update of IP lists" && git push
