name: Generate ADB IP List

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate ADB list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
      - name: Compile CLI
        run: go build -ldflags "-s -w" .

      - name: Update ADB list
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_ENDPOINT: "${{ secrets.AWS_ENDPOINT }}"
          AWS_BUCKET: "${{ secrets.AWS_BUCKET }}"
          ADB_KEY: "${{ secrets.ADB_KEY }}"
        run: |
          ./iplists adb s3-pull $RUNNER_TEMP/adb.json || exit 1
          ./iplists adb fetch $RUNNER_TEMP/adb.json || exit 1
          ./iplists adb build $RUNNER_TEMP/adb.json lists/abuseipdb-30d.txt -d 30 || exit 1
          ./iplists prune lists/abuseipdb-30d.txt lists/icloud-private-relay.txt || exit 1
          ./iplists prune lists/abuseipdb-30d.txt lists/proxies.txt || exit 1
          ./iplists prune lists/abuseipdb-30d.txt lists/tor-exit-nodes.txt || exit 1
          ./iplists prune lists/abuseipdb-30d.txt lists/vpns.txt || exit 1
          ./iplists aggregate lists/abuseipdb-30d.txt -w || exit 1
          [ -s lists/abuseipdb-30d.txt ] || git checkout -- lists/abuseipdb-30d.txt
          ./iplists adb s3-push $RUNNER_TEMP/adb.json || exit 1

      - name: Commit & push updated ADB list
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Hourly auto update of ADB list" && git push
